version: '3.8'

services:
  php81-apache:
    build: .
    image: php:8.1-apache
    container_name: php81-apache
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "4107:80"
    depends_on:
      - mysql80
  
  php81-websocket:
    build: ./websocket_server
    image: php:8.1-cli
    container_name: php81-websocket
    volumes:
      - ./websocket_server:/var/www/html
    working_dir: /var/www/html
    ports:
      - "4109:4109"
    depends_on:
      - mysql80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql80
      PMA_USER: user
      PMA_PASSWORD: userpass
      PMA_DATABASE: db
    ports:
      - "4110:80"
    depends_on:
      - mysql80
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "4111:8080"
    depends_on:
      - mysql80
  
  mysql80:
    image: mysql:8.0
    container_name: mysql80-php81
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
      - TZ=America/Sao_Paulo
    ports:
      - "3341:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
